# Generated by Django 5.2.1 on 2025-05-09 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidades',
            fields=[
                ('especialidad_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_especialidad', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Especialidad',
                'verbose_name_plural': 'Especialidades',
            },
        ),
        migrations.CreateModel(
            name='PeriodoAcademico',
            fields=[
                ('periodo_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_periodo', models.CharField(max_length=50, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Período Académico',
                'verbose_name_plural': 'Períodos Académicos',
                'ordering': ['-fecha_inicio', 'nombre_periodo'],
            },
        ),
        migrations.CreateModel(
            name='TiposEspacio',
            fields=[
                ('tipo_espacio_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_espacio', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Espacio',
                'verbose_name_plural': 'Tipos de Espacios',
            },
        ),
        migrations.CreateModel(
            name='UnidadAcademica',
            fields=[
                ('unidad_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_unidad', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Unidad Académica',
                'verbose_name_plural': 'Unidades Académicas',
            },
        ),
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('materia_id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_materia', models.CharField(max_length=50, unique=True)),
                ('nombre_materia', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('horas_academicas_teoricas', models.IntegerField(default=0)),
                ('horas_academicas_practicas', models.IntegerField(default=0)),
                ('horas_academicas_laboratorio', models.IntegerField(default=0)),
                ('estado', models.BooleanField(default=True)),
                ('requiere_tipo_espacio_especifico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materias_requeridas', to='academic_setup.tiposespacio')),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
            },
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('carrera_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_carrera', models.CharField(max_length=255)),
                ('codigo_carrera', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('horas_totales_curricula', models.IntegerField(blank=True, null=True)),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carreras', to='academic_setup.unidadacademica')),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
                'unique_together': {('nombre_carrera', 'unidad')},
            },
        ),
        migrations.CreateModel(
            name='MateriaEspecialidadesRequeridas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_setup.especialidades')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_setup.materias')),
            ],
            options={
                'verbose_name': 'Especialidad Requerida por Materia',
                'verbose_name_plural': 'Especialidades Requeridas por Materias',
                'unique_together': {('materia', 'especialidad')},
            },
        ),
        migrations.CreateModel(
            name='CarreraMaterias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciclo_sugerido', models.IntegerField(blank=True, null=True)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_setup.carrera')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_setup.materias')),
            ],
            options={
                'verbose_name': 'Materia de Carrera',
                'verbose_name_plural': 'Materias de Carreras',
                'unique_together': {('carrera', 'materia')},
            },
        ),
        migrations.CreateModel(
            name='EspaciosFisicos',
            fields=[
                ('espacio_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_espacio', models.CharField(max_length=100)),
                ('capacidad', models.IntegerField(blank=True, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('recursos_adicionales', models.TextField(blank=True, null=True)),
                ('tipo_espacio', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='espacios', to='academic_setup.tiposespacio')),
                ('unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='espacios_fisicos', to='academic_setup.unidadacademica')),
            ],
            options={
                'verbose_name': 'Espacio Físico',
                'verbose_name_plural': 'Espacios Físicos',
                'unique_together': {('nombre_espacio', 'unidad')},
            },
        ),
    ]
