# Generated by Django 5.2.1 on 2025-05-14 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_setup', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('rol_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='DocenteEspecialidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_setup.especialidades')),
            ],
            options={
                'verbose_name': 'Especialidad de Docente',
                'verbose_name_plural': 'Especialidades de Docentes',
            },
        ),
        migrations.CreateModel(
            name='Docentes',
            fields=[
                ('docente_id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_docente', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('dni', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo_contrato', models.CharField(blank=True, max_length=50, null=True)),
                ('max_horas_semanales', models.IntegerField(blank=True, null=True)),
                ('especialidades', models.ManyToManyField(blank=True, through='users.DocenteEspecialidades', to='academic_setup.especialidades')),
                ('unidad_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docentes', to='academic_setup.unidadacademica')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_docente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
            },
        ),
        migrations.AddField(
            model_name='docenteespecialidades',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.docentes'),
        ),
        migrations.CreateModel(
            name='SesionesUsuario',
            fields=[
                ('sesion_id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=500, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_activas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión de Usuario',
                'verbose_name_plural': 'Sesiones de Usuarios',
            },
        ),
        migrations.AlterUniqueTogether(
            name='docenteespecialidades',
            unique_together={('docente', 'especialidad')},
        ),
    ]
